# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stagecoach < Formula
  desc "Snapshot-based AI commit message generator that uses YOUR local CLI agent"
  homepage "https://github.com/dabstractor/stagecoach"
  version "0.1.14"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dabstractor/stagecoach/releases/download/v0.1.14/stagecoach_0.1.14_darwin_amd64.tar.gz"
      sha256 "b9b7f89146772c736513037e08fa4a4b081df88eec6d96495bca8f8cfd6f1268"

      define_method(:install) do
        bin.install "stagecoach"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dabstractor/stagecoach/releases/download/v0.1.14/stagecoach_0.1.14_darwin_arm64.tar.gz"
      sha256 "d09955dd08a404f0d86d9fb977181595b0573ac5a7a87ed42a604ec7b35a2c06"

      define_method(:install) do
        bin.install "stagecoach"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dabstractor/stagecoach/releases/download/v0.1.14/stagecoach_0.1.14_linux_amd64.tar.gz"
      sha256 "d0f085767b8ee80803b833c4a09dfbe65086508b5c37c20a50da667ba041dadb"
      define_method(:install) do
        bin.install "stagecoach"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dabstractor/stagecoach/releases/download/v0.1.14/stagecoach_0.1.14_linux_arm64.tar.gz"
      sha256 "89b79dea7a35342c15d28a5b7d13b89ac175dc6f19f659e64192d7e4f6a2f121"
      define_method(:install) do
        bin.install "stagecoach"
      end
    end
  end
end
