# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stagecoach < Formula
  desc "Snapshot-based AI commit message generator that uses YOUR local CLI agent"
  homepage "https://github.com/dabstractor/stagecoach"
  version "0.1.15"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dabstractor/stagecoach/releases/download/v0.1.15/stagecoach_0.1.15_darwin_amd64.tar.gz"
      sha256 "7c8768b9ccc45ebe9ab9a76fd26e3e501ca1a497221cddd9e79a587f78f6b363"

      define_method(:install) do
        bin.install "stagecoach"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dabstractor/stagecoach/releases/download/v0.1.15/stagecoach_0.1.15_darwin_arm64.tar.gz"
      sha256 "58cfa62469884ed67b8b9e331166e5ed01d737a12881eb67a6f00dec395f78a5"

      define_method(:install) do
        bin.install "stagecoach"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dabstractor/stagecoach/releases/download/v0.1.15/stagecoach_0.1.15_linux_amd64.tar.gz"
      sha256 "364187b101813d1a7b2bcabe6ad76c8d247ef95854aea7fa1300a580fb5bf8be"
      define_method(:install) do
        bin.install "stagecoach"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dabstractor/stagecoach/releases/download/v0.1.15/stagecoach_0.1.15_linux_arm64.tar.gz"
      sha256 "6f1f222c63e4dc977ba010a966920032f28f615cc56f661b5262fe4350663824"
      define_method(:install) do
        bin.install "stagecoach"
      end
    end
  end
end
